mssql:
  sqlhost: ''
  database: ''
  username: ''
  password: ''
  driver_config_url: 'https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17'
get_connected:
  api_key_secret: ''
  entity_list:
    - 'volunteer/agency'
    - 'volunteer/need'
    - 'volunteer/response'
    - 'volunteer/user'
  api_documentation_url : 'http://api2.galaxydigital.com/volunteer/docs/'
  row_limit: '0'